name: "Terraform Infrastructure"

on:
  push:
    branches: ["main"]
    paths: ["terraform/**"] # Only run if TF files change

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to checkout code

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_sql_admin_login: ${{ secrets.TF_VAR_sql_admin_login }}
  TF_VAR_sql_admin_password: ${{ secrets.TF_VAR_sql_admin_password }}
  ARM_USE_OIDC: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
